server:
  port: ${PORT:8400}
spring:
  application:
    name: order-api
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb-order
    username: sa
    password:
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  
