server: 
  port: ${PORT:8200}
spring:
  application:
    name: client-api
  H2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb-client
    username: sa
    password: 
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}