server:
  port: ${PORT:8301}
spring:
  application:
    name: product-api
  H2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb-product
    username: sa
    password:
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  